AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 5
    Runtime: nodejs12.x
    Environment:
      Variables:
        TABLE_NAME: !Ref Table
        SQS_URL: !Ref Queue

Resources:
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: name
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  Queue:
    Type: AWS::SQS::Queue
  SendSQS:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api-sqs-function/built
      Handler: api-sqs.Send_Data
      Policies: AmazonSQSFullAccess
      Events:
        SendSQS:
          Type: Api
          Properties:
            Path: /senddata/sqs
            Method: post
  SaveComment:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sqs-ddb-function/built
      Handler: sqs-ddb.Receive_Data
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSQSFullAccess
      Events:
        SaveComment:
          Type: SQS
          Properties:
            Queue: !GetAtt Queue.Arn
  ReadComments:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ddb-api-function/built
      Handler: ddb-api.Get_Data
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        ReadComments:
          Type: Api
          Properties:
            Path: /get/data
            Method: get